### ISSUE TITLE
挺期待的！

### ISSUE THREAD

**Issue by Whitolf** [ZhuYanzhen1/miniFOC#1]
期待大佬更新！另外有几个问题：1.驱动电流是不是可以通过更换mos管获得更大的电流？2.Simplefoc好像支持了foc电流模式？

**Comment by ZhuYanzhen1** [comment]
> 
> 
> 期待大佬更新！另外有几个问题：1.驱动电流是不是可以通过更换mos管获得更大的电流？2.Simplefoc好像支持了foc电流模式？

感谢关注！对于你的问题：
1. 可以通过更换MOS管获得更大的电流，请关注后续更新的教程
2. simpleFOC有支持电流环的branch，但是尚不十分稳定。在我移植该branch时发现效果并不理想。
3. 持续关注本项目，在未来有加入电流环的计划。
