### ISSUE TITLE
[Feature] FOC调制算法似乎不是SVPWM？

### ISSUE THREAD

**Issue by HangX-Ma** [ZhuYanzhen1/miniFOC#12]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求<br> I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) 并无法自行解决问题 I have read the [documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) and was unable to solve the issue. 

### Description

`foc_calculate_dutycycle()`这个函数计算的是FOC三相电压的输出，但是计算方法看着并非是SVPWM而是SinePWM。
在SimpleFOC给的描述中SinePWM的计算方法包括Inverse Park transformation和Inverse Clarke transformation，计算方式如下:
- Inverse Park transformation

$$U_{\alpha}=U_d*cos(\theta)-U_q*sin(\theta)$$

$$U_{\beta}=U_d*sin(\theta)+U_q*sin(\theta)$$

一般只需要切向的$U_q$而不需要径向的$U_d$，故而$U_d=0$是期望值。
- Inverse Clarke transformation

$$u_a=U_{\alpha}$$

$$u_b=\frac{-U_{\alpha}+\sqrt{3}U_{\beta}}{2}$$

$$u_b=\frac{-U_{\alpha}-\sqrt{3}U_{\beta}}{2}$$

在作者的设计代码中是这样处理的：
```c
void foc_calculate_dutycycle(float elect_angle, float d, float q, float *u, float *v, float *w) {
    float alpha, beta;

    /* fast calculation of cosine and sine value of electric angle */
    float cf = fast_cos(elect_angle);
    float sf = fast_sin(elect_angle);

    /* firstly, the inverse Park transform is calculated */
    alpha = d * cf - q * sf;
    beta = q * cf + d * sf;

    /* secondly, the inverse Clarke transform is calculated */
    *u = 0.5f - alpha / VBUS;
    *v = 0.5f + (alpha * 0.5f - beta * 0.866025404f) / VBUS;
    *w = 1.5f - *u - *v;
}
```
`0.5`以及`0.15`这样奇怪的常量设置能否解释一下具体原因，以及整体计算方式应当归为SinePWM调制而不是SVPWM，与您的工程描述相悖。
@

**Comment by ZhuYanzhen1** [comment]
感谢您提出上述问题。在初期开发版本[2d309e904e5c3ea1071f60b64bcca6f0a0b3b80f](https://github.com/ZhuYanzhen1/miniFOC/commit/2d309e904e5c3ea1071f60b64bcca6f0a0b3b80f)中使用的是SVPWM，后续忘记更改回来了。现在仓库中已经更新该调制方法，并可以通过宏进行切换。值`0.5`和`1.5`是由于PWM产生方式被设置为了中央对齐，所以需要提供一个中间占空比的偏置使得负值能够被接受。

**Comment by HangX-Ma** [comment]
感谢您的及时回复与更正解答，期待更多的学习与技术探讨。
