### ISSUE TITLE
支持步进电机吗

### ISSUE THREAD

**Issue by Mountain03** [ZhuYanzhen1/miniFOC#15]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求<br> I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) 并无法自行解决问题 I have read the [documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) and was unable to solve the issue. 

### Description

步进电机支持吗,有方案吗

**Comment by ZhuYanzhen1** [comment]
目前还不支持，miniFOC是为BLDC开发的驱动方案。
