### ISSUE TITLE
[Feature] 无感FOC

### ISSUE THREAD

**Issue by asanghehe** [ZhuYanzhen1/miniFOC#3]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求<br> I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) 并无法自行解决问题 I have read the [documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) and was unable to solve the issue. 

### Description

这个项目目前只是有感FOC的实现吧，有计划做无感的吗

**Comment by ZhuYanzhen1** [comment]
此项目目前只是有感FOC，对于无感FOC而言这颗控制器无法提供足够的算力进行观测器部分有关的计算。如果你有加速运算的思路或者有关算法能够提供，请提交PR参与我们的开发。

**Comment by asanghehe** [comment]
> 
> 
> 此项目目前只是有感FOC，对于无感FOC而言这颗控制器无法提供足够的算力进行观测器部分有关的计算。如果你有加速运算的思路或者有关算法能够提供，请提交PR参与我们的开发。

我看了电路图，不知道那个传感器是怎么个安装方式，能否上传个真机照片看看呢

**Comment by ZhuYanzhen1** [comment]
> 
> 
> > 此项目目前只是有感FOC，对于无感FOC而言这颗控制器无法提供足够的算力进行观测器部分有关的计算。如果你有加速运算的思路或者有关算法能够提供，请提交PR参与我们的开发。
> 
> 我看了电路图，不知道那个传感器是怎么个安装方式，能否上传个真机照片看看呢

传感器电路的安装上的图片如下：
![8d97cdbebc48157e0db61c769898e62.jpg](https://i.loli.net/2021/09/17/ZjFJc1ktLid32zM.jpg)
后期我们会在wiki上补充更清晰详细的安装说明，预计九月底wiki页面会基本补全。
