### ISSUE TITLE
[Feature] 是否可能移植到 esp32 的Arduino平台？

### ISSUE THREAD

**Issue by ifengchao** [ZhuYanzhen1/miniFOC#7]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求<br> I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) 并无法自行解决问题 I have read the [documentation](https://github.com/ZhuYanzhen1/miniFOC/wiki) and was unable to solve the issue. 

### Description

能放出开源代码，已经很了不起了！非常感谢！

### Possible Solution

如果可以支持ESP32的Arduino平台开发，相信更容易推荐开源软件的传播。
而且ESP32似乎在性能和功能上比GD32更有优势，更容易拓展。单价也很低。

**Comment by ZhuYanzhen1** [comment]
> 如果可以支持ESP32的Arduino平台开发，相信更容易推荐开源软件的传播。 而且ESP32似乎在性能和功能上比GD32更有优势，更容易拓展。单价也很低。

ESP32的性能确实强于我选的这款GD32，不过它在小型化和成本上还没有压倒性的优势。这个想法很好，我之前也有想过是否要支持Arduino，无奈学业繁忙没有精力再做移植和适配。如果你有想法和能力的话可以提交pull request或者创建一个新branch进行开发。

**Comment by ifengchao** [comment]
> > 如果可以支持ESP32的Arduino平台开发，相信更容易推荐开源软件的传播。 而且ESP32似乎在性能和功能上比GD32更有优势，更容易拓展。单价也很低。
> 
> ESP32的性能确实强于我选的这款GD32，不过它在小型化和成本上还没有压倒性的优势。这个想法很好，我之前也有想过是否要支持Arduino，无奈学业繁忙没有精力再做移植和适配。如果你有想法和能力的话可以提交pull request或者创建一个新branch进行开发。

有时间我也会试着尝试，如果我能全部理解你的代码。

**Comment by ifengchao** [comment]
http://simplefoc.cn/#/simplefoc_translation/3.7%E6%8A%80%E6%9C%AF%E8%B7%AF%E7%BA%BF
刚刚看到灯哥开源介绍的simplefoc路线，他们对ESP32做了支持，关注的伙伴可以了解下。

**Comment by microcai** [comment]
ESP32 有 freertos 和 ardunio 两种平台。建议直接用 freertos 的。ardunio 平台封装的非常臃肿，加个电机库后， flash 就快吃完了。没法加 wifi 了。
